services:
  iron-log:
    build: .
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - iron-log-data:/app/data
    restart: unless-stopped
    networks:
      - proxy_netzwerk

volumes:
  iron-log-data:

networks:
  proxy_netzwerk:
    external: true
